<?php

/**
 * @module_name gusev_analytics_page
 */

        const ADMIN_CONFIG_GUSEV_ANALYTICS_PAGES = 'admin/config/gusev_analytics/page';

/**
 * Implements hook_menu().
 */
function gusev_analytics_page_menu() {
    $items[ADMIN_CONFIG_GUSEV_ANALYTICS_PAGES] = array(
        'title' => t('Pages analytics'),
        'page callback' => 'gusev_analytics_admin_page',
        'access arguments' => array('administer users'),
        'file' => 'gusev_analytics_page.page.inc',
        'file path' => drupal_get_path('module', 'gusev_analytics_page')
    );
    return $items;
}

/**
 * Implements hook_theme().
 */
function gusev_analytics_page_theme() {
    return array(
        'gusev_analytics_page_statistic' => array(
            'variables' => array(),
            'template' => 'gusev-analytics-page-statistic',
        ),
    );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function gusev_analytics_page_preprocess_node(&$variables) {
    if ($variables['page'] == true) {
        global $user;
        if ($user->uid != 0) {
            $time = time();
            db_merge('gusev_analytics_page_pages_viewed')
                    ->key(
                            array(
                                'uid' => $user->uid,
                                'nid' => $variables['nid'],
                                'viewing_time' => $time
                            )
                    )
                    ->fields(
                            array(
                                'uid' => $user->uid,
                                'nid' => $variables['nid'],
                                'viewing_time' => $time
                            )
                    )
                    ->execute();



            /*  db_insert('gusev_analytics_page_pages_viewed')
              ->fields(array(
              'uid' => $user->uid,
              'nid' => $variables['nid'],
              ))
              ->execute(); */
        }
    }
}

function _gusev_analytics_page_statistic_render() {
    $filter_data = isset($_SESSION['gusev_analytics_pages_form']) ? $_SESSION['gusev_analytics_pages_form'] : array();
    $type = $filter_data['type'][0];
    $specialization = $filter_data['specialization'][0];
    switch ($type) {
        case 0:
            $return['pages_viewed'] = _gusev_analytics_page_get_pages_viewed($specialization);
            break;
        case 1:
            $return['pages_viewed'] = _gusev_analytics_page_get_unique_pageviews($specialization);
            break;
        default:
            $return['pages_viewed'] = _gusev_analytics_page_get_pages_viewed($specialization);
            break;
    }


    return theme('gusev_analytics_page_statistic', $return);
}

function _gusev_analytics_page_get_pages_viewed($specialization) {
    $query = db_select('gusev_analytics_page_pages_viewed', 'pv');
    $query->fields('pv', array('nid'));
    if($specialization != '-1'){
        $query->innerJoin('field_data_field_specialization', 'specialization', 'specialization.entity_id = pv.uid');
        $query->where('specialization.field_specialization_tid = :tid', array(':tid' => $specialization));
    }
    $query->innerJoin('node', 'n', 'n.nid = pv.nid');
    $query->fields('n', array('title'));
    $query->addExpression('COUNT(pv.uid)', 'viewed');
    $query->groupBy('pv.nid');
    $query->orderBy('viewed', 'DESC');
    return $query->execute()->fetchAll();
    //    SELECT node.title, nid, COUNT( uid ) AS viewed
    //    FROM  `gusev_analytics_page_pages_viewed` 
    //    join node on node.nid = gusev_analytics_page_pages_viewed.nid
    //    GROUP BY uid
    //    ORDER BY  `viewed` ASC 
}

function _gusev_analytics_page_get_unique_pageviews($specialization) {
    $query = db_select('gusev_analytics_page_pages_viewed', 'pv');
    $query->fields('pv', array('nid'));
    if($specialization != '-1'){
        $query->innerJoin('field_data_field_specialization', 'specialization', 'specialization.entity_id = pv.uid');
        $query->where('specialization.field_specialization_tid = :tid', array(':tid' => $specialization));
    }
    $query->innerJoin('node', 'n', 'n.nid = pv.nid');
    $query->fields('n', array('title'));
    $query->addExpression('COUNT(DISTINCT pv.uid)', 'viewed');
    $query->groupBy('pv.nid');
    $query->orderBy('viewed', 'DESC');
    return $query->execute()->fetchAll();
    //    SELECT node.title, nid, COUNT(DISTINCT uid ) AS viewed
    //    FROM  `gusev_analytics_page_pages_viewed` 
    //    join node on node.nid = gusev_analytics_page_pages_viewed.nid
    //    GROUP BY uid
    //    ORDER BY  `viewed` ASC 
}
